storageClasses: 
# Add StorageClass resources like:
 - name: ebs-sc
   annotations:
     storageclass.kubernetes.io/is-default-class: "true"
   volumeBindingMode: WaitForFirstConsumer
   reclaimPolicy: Retain
   parameters:
     encrypted: "true"
     type: gp3